name: Update Coin Configs and create 128x128 images in icons dir

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'utils/*.json'
      - 'utils/spritemap.png'

  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_branch:
        description: Branch to run against and target for PR
        required: true
        default: master
        type: string

jobs:
  update_configs:
    runs-on: ubuntu-22.04
    env:
      TARGET_BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target_branch || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}

      - name: Install cargo
        shell: bash
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install cargo cmake autoconf automake libtool nasm make pkg-config rustc -y

      - name: Install oxipng
        shell: bash
        run: |
          cargo install oxipng
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create 128x128 images in icons dir
        shell: bash
        run:  ${GITHUB_WORKSPACE}/utils/icons_resize.sh

      - name: Install dependencies
        shell: bash
        run: pip3 install -r ${GITHUB_WORKSPACE}/utils/requirements.txt

      - name: Validate seed nodes
        continue-on-error: true
        shell: bash
        run: |
          echo "Validating seed-nodes.json before generating configs..."
          python3 ${GITHUB_WORKSPACE}/utils/validate_seed_nodes.py

      - name: Generate configs
        shell: bash
        run: ${GITHUB_WORKSPACE}/utils/generate_app_configs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update coins json file
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          base: ${{ env.TARGET_BRANCH }}
          branch: config-generate/${{ env.TARGET_BRANCH }}
          delete-branch: true
          title: "[BOT] Update coins config json for ${{ env.TARGET_BRANCH }}"
          body: |
            - Coins JSON config auto-generated from `${{ env.TARGET_BRANCH }}`
            - Electrum scan report updated
            - Icon spritemap updated
          labels: |
            config-update
          assignees: yousufpandith
          draft: false
